http:
  host: "0.0.0.0"
  port: "8080"

pg:
  host: "localhost"
  port: "7432"
  database: "order-service"
  sslmode: "disable"

inventory_client:
  address: "localhost:50051"

payment_client:
  address: "localhost:50052"

kafka:
  brokers:
    - "localhost:9092"

order_paid_producer:
  topic: "order.paid"

ship_assembled_consumer:
  topic: "ship.assembled"
  group_id: "order-service"

logger:
  level: "debug"
