// Code generated by mockery. DO NOT EDIT.
// © 1mpuser 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/1mpuser/iam/internal/repository/redis_view"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Create(ctx context.Context, view redisview.SessionRedisView) error {
	ret := _mock.Called(ctx, view)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, redisview.SessionRedisView) error); ok {
		r0 = returnFunc(ctx, view)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - view redisview.SessionRedisView
func (_e *SessionRepository_Expecter) Create(ctx interface{}, view interface{}) *SessionRepository_Create_Call {
	return &SessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, view)}
}

func (_c *SessionRepository_Create_Call) Run(run func(ctx context.Context, view redisview.SessionRedisView)) *SessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 redisview.SessionRedisView
		if args[1] != nil {
			arg1 = args[1].(redisview.SessionRedisView)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Create_Call) Return(err error) *SessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, view redisview.SessionRedisView) error) *SessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Delete(ctx context.Context, uid string) error {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *SessionRepository_Expecter) Delete(ctx interface{}, uid interface{}) *SessionRepository_Delete_Call {
	return &SessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, uid)}
}

func (_c *SessionRepository_Delete_Call) Run(run func(ctx context.Context, uid string)) *SessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Delete_Call) Return(err error) *SessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, uid string) error) *SessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionRepository
func (_mock *SessionRepository) Get(ctx context.Context, uid string) (*redisview.SessionRedisView, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *redisview.SessionRedisView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*redisview.SessionRedisView, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *redisview.SessionRedisView); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redisview.SessionRedisView)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *SessionRepository_Expecter) Get(ctx interface{}, uid interface{}) *SessionRepository_Get_Call {
	return &SessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *SessionRepository_Get_Call) Run(run func(ctx context.Context, uid string)) *SessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepository_Get_Call) Return(sessionRedisView *redisview.SessionRedisView, err error) *SessionRepository_Get_Call {
	_c.Call.Return(sessionRedisView, err)
	return _c
}

func (_c *SessionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, uid string) (*redisview.SessionRedisView, error)) *SessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}
