// Code generated by mockery. DO NOT EDIT.
// © 1mpuser 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/1mpuser/inventory/internal/model"
	"github.com/1mpuser/inventory/internal/repository/record"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PartRepository
func (_mock *PartRepository) Get(ctx context.Context, uuid1 uuid.UUID) (record.Part, error) {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 record.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (record.Part, error)); ok {
		return returnFunc(ctx, uuid1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) record.Part); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		r0 = ret.Get(0).(record.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuid1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PartRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *PartRepository_Expecter) Get(ctx interface{}, uuid1 interface{}) *PartRepository_Get_Call {
	return &PartRepository_Get_Call{Call: _e.mock.On("Get", ctx, uuid1)}
}

func (_c *PartRepository_Get_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *PartRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_Get_Call) Return(part record.Part, err error) *PartRepository_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *PartRepository_Get_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) (record.Part, error)) *PartRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllParts provides a mock function for the type PartRepository
func (_mock *PartRepository) ListAllParts(ctx context.Context) ([]record.Part, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllParts")
	}

	var r0 []record.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]record.Part, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []record.Part); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]record.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_ListAllParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllParts'
type PartRepository_ListAllParts_Call struct {
	*mock.Call
}

// ListAllParts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PartRepository_Expecter) ListAllParts(ctx interface{}) *PartRepository_ListAllParts_Call {
	return &PartRepository_ListAllParts_Call{Call: _e.mock.On("ListAllParts", ctx)}
}

func (_c *PartRepository_ListAllParts_Call) Run(run func(ctx context.Context)) *PartRepository_ListAllParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PartRepository_ListAllParts_Call) Return(parts []record.Part, err error) *PartRepository_ListAllParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_ListAllParts_Call) RunAndReturn(run func(ctx context.Context) ([]record.Part, error)) *PartRepository_ListAllParts_Call {
	_c.Call.Return(run)
	return _c
}

// ListPartsByPartType provides a mock function for the type PartRepository
func (_mock *PartRepository) ListPartsByPartType(ctx context.Context, partType model.PartType) ([]record.Part, error) {
	ret := _mock.Called(ctx, partType)

	if len(ret) == 0 {
		panic("no return value specified for ListPartsByPartType")
	}

	var r0 []record.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartType) ([]record.Part, error)); ok {
		return returnFunc(ctx, partType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartType) []record.Part); ok {
		r0 = returnFunc(ctx, partType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]record.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartType) error); ok {
		r1 = returnFunc(ctx, partType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_ListPartsByPartType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPartsByPartType'
type PartRepository_ListPartsByPartType_Call struct {
	*mock.Call
}

// ListPartsByPartType is a helper method to define mock.On call
//   - ctx context.Context
//   - partType model.PartType
func (_e *PartRepository_Expecter) ListPartsByPartType(ctx interface{}, partType interface{}) *PartRepository_ListPartsByPartType_Call {
	return &PartRepository_ListPartsByPartType_Call{Call: _e.mock.On("ListPartsByPartType", ctx, partType)}
}

func (_c *PartRepository_ListPartsByPartType_Call) Run(run func(ctx context.Context, partType model.PartType)) *PartRepository_ListPartsByPartType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartType
		if args[1] != nil {
			arg1 = args[1].(model.PartType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_ListPartsByPartType_Call) Return(parts []record.Part, err error) *PartRepository_ListPartsByPartType_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_ListPartsByPartType_Call) RunAndReturn(run func(ctx context.Context, partType model.PartType) ([]record.Part, error)) *PartRepository_ListPartsByPartType_Call {
	_c.Call.Return(run)
	return _c
}

// ListPartsByUuids provides a mock function for the type PartRepository
func (_mock *PartRepository) ListPartsByUuids(ctx context.Context, uuids []uuid.UUID) ([]record.Part, error) {
	ret := _mock.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for ListPartsByUuids")
	}

	var r0 []record.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]record.Part, error)); ok {
		return returnFunc(ctx, uuids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []record.Part); ok {
		r0 = returnFunc(ctx, uuids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]record.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uuids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PartRepository_ListPartsByUuids_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPartsByUuids'
type PartRepository_ListPartsByUuids_Call struct {
	*mock.Call
}

// ListPartsByUuids is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []uuid.UUID
func (_e *PartRepository_Expecter) ListPartsByUuids(ctx interface{}, uuids interface{}) *PartRepository_ListPartsByUuids_Call {
	return &PartRepository_ListPartsByUuids_Call{Call: _e.mock.On("ListPartsByUuids", ctx, uuids)}
}

func (_c *PartRepository_ListPartsByUuids_Call) Run(run func(ctx context.Context, uuids []uuid.UUID)) *PartRepository_ListPartsByUuids_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PartRepository_ListPartsByUuids_Call) Return(parts []record.Part, err error) *PartRepository_ListPartsByUuids_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *PartRepository_ListPartsByUuids_Call) RunAndReturn(run func(ctx context.Context, uuids []uuid.UUID) ([]record.Part, error)) *PartRepository_ListPartsByUuids_Call {
	_c.Call.Return(run)
	return _c
}
