// Code generated by mockery. DO NOT EDIT.
// © 1mpuser 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/1mpuser/order/internal/model"
	"github.com/1mpuser/order/internal/repository/record"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Create(ctx context.Context, order record.Order, orderItems []record.OrderItem) error {
	ret := _mock.Called(ctx, order, orderItems)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, record.Order, []record.OrderItem) error); ok {
		r0 = returnFunc(ctx, order, orderItems)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order record.Order
//   - orderItems []record.OrderItem
func (_e *OrderRepository_Expecter) Create(ctx interface{}, order interface{}, orderItems interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order, orderItems)}
}

func (_c *OrderRepository_Create_Call) Run(run func(ctx context.Context, order record.Order, orderItems []record.OrderItem)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 record.Order
		if args[1] != nil {
			arg1 = args[1].(record.Order)
		}
		var arg2 []record.OrderItem
		if args[2] != nil {
			arg2 = args[2].([]record.OrderItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(err error) *OrderRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, order record.Order, orderItems []record.OrderItem) error) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Get(ctx context.Context, id uuid.UUID) (*record.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *record.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*record.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *record.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OrderRepository_Expecter) Get(ctx interface{}, id interface{}) *OrderRepository_Get_Call {
	return &OrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *OrderRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_Get_Call) Return(order *record.Order, err error) *OrderRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*record.Order, error)) *OrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetForUpdate provides a mock function for the type OrderRepository
func (_mock *OrderRepository) GetForUpdate(ctx context.Context, id uuid.UUID) (*record.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetForUpdate")
	}

	var r0 *record.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*record.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *record.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*record.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepository_GetForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForUpdate'
type OrderRepository_GetForUpdate_Call struct {
	*mock.Call
}

// GetForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OrderRepository_Expecter) GetForUpdate(ctx interface{}, id interface{}) *OrderRepository_GetForUpdate_Call {
	return &OrderRepository_GetForUpdate_Call{Call: _e.mock.On("GetForUpdate", ctx, id)}
}

func (_c *OrderRepository_GetForUpdate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OrderRepository_GetForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepository_GetForUpdate_Call) Return(order *record.Order, err error) *OrderRepository_GetForUpdate_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepository_GetForUpdate_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*record.Order, error)) *OrderRepository_GetForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function for the type OrderRepository
func (_mock *OrderRepository) Pay(ctx context.Context, orderId uuid.UUID, paymentMethod model.PaymentMethod, transactionId uuid.UUID) error {
	ret := _mock.Called(ctx, orderId, paymentMethod, transactionId)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.PaymentMethod, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderId, paymentMethod, transactionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderRepository_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderId uuid.UUID
//   - paymentMethod model.PaymentMethod
//   - transactionId uuid.UUID
func (_e *OrderRepository_Expecter) Pay(ctx interface{}, orderId interface{}, paymentMethod interface{}, transactionId interface{}) *OrderRepository_Pay_Call {
	return &OrderRepository_Pay_Call{Call: _e.mock.On("Pay", ctx, orderId, paymentMethod, transactionId)}
}

func (_c *OrderRepository_Pay_Call) Run(run func(ctx context.Context, orderId uuid.UUID, paymentMethod model.PaymentMethod, transactionId uuid.UUID)) *OrderRepository_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.PaymentMethod
		if args[2] != nil {
			arg2 = args[2].(model.PaymentMethod)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *OrderRepository_Pay_Call) Return(err error) *OrderRepository_Pay_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_Pay_Call) RunAndReturn(run func(ctx context.Context, orderId uuid.UUID, paymentMethod model.PaymentMethod, transactionId uuid.UUID) error) *OrderRepository_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type OrderRepository
func (_mock *OrderRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status model.OrderStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type OrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status model.OrderStatus
func (_e *OrderRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *OrderRepository_UpdateStatus_Call {
	return &OrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *OrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status model.OrderStatus)) *OrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 model.OrderStatus
		if args[2] != nil {
			arg2 = args[2].(model.OrderStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepository_UpdateStatus_Call) Return(err error) *OrderRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status model.OrderStatus) error) *OrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
