// Code generated by mockery. DO NOT EDIT.
// © 1mpuser 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/1mpuser/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderProducer creates a new instance of OrderProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProducer {
	mock := &OrderProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderProducer is an autogenerated mock type for the OrderProducer type
type OrderProducer struct {
	mock.Mock
}

type OrderProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderProducer) EXPECT() *OrderProducer_Expecter {
	return &OrderProducer_Expecter{mock: &_m.Mock}
}

// ProduceOrderPaid provides a mock function for the type OrderProducer
func (_mock *OrderProducer) ProduceOrderPaid(ctx context.Context, event model.OrderPaid) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderPaid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.OrderPaid) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderProducer_ProduceOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderPaid'
type OrderProducer_ProduceOrderPaid_Call struct {
	*mock.Call
}

// ProduceOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaid
func (_e *OrderProducer_Expecter) ProduceOrderPaid(ctx interface{}, event interface{}) *OrderProducer_ProduceOrderPaid_Call {
	return &OrderProducer_ProduceOrderPaid_Call{Call: _e.mock.On("ProduceOrderPaid", ctx, event)}
}

func (_c *OrderProducer_ProduceOrderPaid_Call) Run(run func(ctx context.Context, event model.OrderPaid)) *OrderProducer_ProduceOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.OrderPaid
		if args[1] != nil {
			arg1 = args[1].(model.OrderPaid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderProducer_ProduceOrderPaid_Call) Return(err error) *OrderProducer_ProduceOrderPaid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderProducer_ProduceOrderPaid_Call) RunAndReturn(run func(ctx context.Context, event model.OrderPaid) error) *OrderProducer_ProduceOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}
